name: rainbow
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1

  page_transition: ^1.1.7+5
  provider: ^4.3.2+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  word_search: ^0.1.2
  string_scanner: ^1.1.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
  custom_navigation_bar: ^0.7.0



  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  flutter_fortune_wheel: ^0.3.6
  audioplayers: 0.15.0
  numberpicker: ^1.0.0
  carousel_pro: ^1.0.0

  path_provider:





dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/dot.jpg
    - assets/nature.jpg
    - assets/3minToon.jpg
    - assets/nature2.jpg
    - assets/note.jpg
    - assets/dial.jpg
    - assets/star1.jpg
    - assets/star4.jpg
    - assets/star5.jpg
    - assets/star6.jpg
    - assets/star8.jpg
    - assets/star9.jpg
    - assets/star10.jpg
    - assets/star11.jpg
    - assets/star12.jpg
    - assets/star13.jpg
    - assets/star14.jpg
    - assets/star15.jpg
    - assets/star16.jpg
    - assets/star19.jpg
    - assets/star20.jpg
    - assets/star21.jpg
    - assets/star22.jpg
    - assets/star23.jpg
    - assets/star25.jpg
    - assets/star26.jpg
    - assets/star27.jpg
    - assets/star28.jpg
    - assets/star29.jpg
    - assets/star30.jpg
    - assets/star32.jpg
    - assets/star33.jpg
    - assets/star34.jpg
    - assets/star35.jpg
    - assets/8d82b5_Letter_X_Sound_Effect.mp3
    - assets/Cosmos1.m4a
    - assets/flute.m4a
    - assets/meditate.jpg
    - assets/Anxiety1.jpg
    - assets/Anxiety2.jpg
    - assets/Anxiety3.jpg
    - assets/Anxiety4.jpg
    - assets/Anxiety5.jpg
    - assets/Anxiety6.jpg
    - assets/Anxiety7.jpg
    - assets/Anxiety8.jpg
    - assets/Anxiety9.jpg
    - assets/Anxiety10.jpg
    - assets/Yognidra.jpg
    - assets/Diary.jpg
    - assets/Number.jpg
    - assets/Word.jpg
    - assets/Diary1.jpg
    - assets/quiz.jpg
    - assets/Diary2.jpg
    - assets/Diary3.jpg
    - assets/meditation1.jpg
    - assets/meditation2.jpg
    - assets/meditation3.jpg
    - assets/meditation4.jpg
    - assets/comm1.jpg
    - assets/comm2.jpg
    - assets/comm3.jpg
    - assets/comm4.jpg
    - assets/comm5.jpg
    - assets/rainbowImage.jpg
    - assets/Diary4.jpg



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Monteserat.ttf